#cloud-config

hostname: wazuh
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - openssh-server
  - curl
  - wget
  - ca-certificates
  - docker.io

write_files:
  - path: /opt/wazuh/dashboard-config/opensearch_dashboards.yml
    owner: root:root
    permissions: '0644'
    content: |
      server.host: "0.0.0.0"
      server.port: 5601

      opensearch.hosts:
        - https://indexer:9200

      opensearch.ssl.verificationMode: none

      opensearch.requestHeadersWhitelist: [ authorization, securitytenant ]

      opensearch.username: "admin"
      opensearch.password: "admin"

      opensearch_security.multitenancy.enabled: true
      opensearch_security.readonly_mode.roles: ["kibana_read_only"]
      opensearch_security.cookie.secure: false

  - path: /opt/wazuh/docker-compose.yml
    owner: root:root
    permissions: '0644'
    content: |
        services:
          indexer:
            image: wazuh/wazuh-indexer:4.14.1
            hostname: indexer
            ports:
              - "9200:9200"
            environment:
              - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
            ulimits:
              memlock:
                soft: -1
                hard: -1
        
          manager:
            image: wazuh/wazuh-manager:4.14.1
            hostname: manager
            ports:
              - "1514:1514/udp"
              - "1515:1515"
              - "55000:55000"
        
          dashboard:
            image: wazuh/wazuh-dashboard:4.14.1
            hostname: dashboard
            depends_on:
              - indexer
            ports:
              - "80:5601"
            volumes:
              - /opt/wazuh/dashboard-config:/usr/share/wazuh-dashboard/config:ro
            restart: always

runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable ssh --now
  - systemctl enable qemu-guest-agent
  - mkdir -p /opt/wazuh
  - cd /opt/wazuh
#  - docker compose -f /opt/wazuh/docker-compose.yml up -d
