#cloud-config
hostname: wazuh
manage_etc_hosts: true

network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - 192.168.2.20/24
      gateway4: 192.168.2.1
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]

    eth1:
      dhcp4: false
      addresses:
        - 172.20.0.20/24
