#cloud-config

hostname: wazuh
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - openssh-server
  - curl
  - wget
  - ca-certificates
  - docker.io

runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable ssh --now
  - systemctl enable qemu-guest-agent
  - cd /opt/
  - git clone https://github.com/wazuh/wazuh-docker.git -b v4.14.1
  - cd /opt/wazuh-docker/single-node
  - docker compose -f generate-indexer-certs.yml run --rm generator
  - docker compose up -d
  
