#cloud-config

hostname: wazuh
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - openssh-server
  - curl
  - wget
  - ca-certificates
  - docker.io

write_files:
  - path: /opt/wazuh/generate-indexer-certs.yml
    owner: root:root
    permissions: '0644'
    content: |
      services:
        generator:
            image: wazuh/wazuh-certs-generator:0.0.3
            hostname: wazuh-certs-generator
            environment:
              - CERT_TOOL_VERSION=4.14
            volumes:
              - ./config/wazuh_indexer_ssl_certs/:/certificates/
              - ./config/certs.yml:/config/certs.yml
  - path: /opt/wazuh/docker-compose.yml
    owner: root:root
    permissions: '0644'
    content: |
    version: "3.9"

      services:

        indexer:
          image: wazuh/wazuh-indexer:latest
          hostname: indexer
          ports:
            - "9200:9200"
          environment:
            - OPENSEARCH_SECURITY_SSL_HTTP_ENABLED=true
            - OPENSEARCH_SECURITY_SSL_HTTP_KEY=/certs/indexer.key
            - OPENSEARCH_SECURITY_SSL_HTTP_CERTIFICATE=/certs/indexer.crt
            - OPENSEARCH_SECURITY_SSL_HTTP_PEMTRUSTEDCAS=/certs/rootCA.crt
          volumes:
            - /opt/wazuh/certs:/certs:ro

        manager:
          image: wazuh/wazuh-manager:latest
          hostname: manager
          ports:
            - "1514:1514/udp"
            - "1515:1515"
            - "55000:55000"
          environment:
            - WAZUH_SSL_CERTIFICATE=/certs/manager.crt
            - WAZUH_SSL_KEY=/certs/manager.key
            - WAZUH_SSL_CA=/certs/rootCA.crt
          volumes:
            - /opt/wazuh/certs:/certs:ro

        dashboard:
          image: wazuh/wazuh-dashboard:latest
          hostname: dashboard
          depends_on:
            - indexer
          ports:
            - "80:5601"
          environment:
            - WAZUH_DASHBOARD_SSL_CERTIFICATE=/certs/dashboard.crt
            - WAZUH_DASHBOARD_SSL_KEY=/certs/dashboard.key
          volumes:
            - /opt/wazuh/certs:/certs:ro
runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable ssh --now
  - systemctl enable qemu-guest-agent
  - mkdir -p /opt/wazuh
  - mkdir -p /opt/wazuh/certs
  - cd /opt/wazuh
  # --- Generate CA ---
  - openssl genrsa -out /opt/wazuh/certs/rootCA.key 4096
  - openssl req -x509 -new -nodes -key /opt/wazuh/certs/rootCA.key -sha256 -days 3650 -subj "/CN=wazuh-rootCA" -out /opt/wazuh/certs/rootCA.crt
  # Indexer cert
  - openssl genrsa -out /opt/wazuh/certs/indexer.key 2048
  - openssl req -new -key /opt/wazuh/certs/indexer.key -subj "/CN=indexer" -out /opt/wazuh/certs/indexer.csr
  - openssl x509 -req -in /opt/wazuh/certs/indexer.csr -CA /opt/wazuh/certs/rootCA.crt -CAkey /opt/wazuh/certs/rootCA.key -CAcreateserial -out /opt/wazuh/certs/indexer.crt -days 365 -sha256
  # Manager cert
  - openssl genrsa -out /opt/wazuh/certs/manager.key 2048
  - openssl req -new -key /opt/wazuh/certs/manager.key -subj "/CN=manager" -out /opt/wazuh/certs/manager.csr
  - openssl x509 -req -in /opt/wazuh/certs/manager.csr -CA /opt/wazuh/certs/rootCA.crt -CAkey /opt/wazuh/certs/rootCA.key -CAcreateserial -out /opt/wazuh/certs/manager.crt -days 365 -sha256
  # Dashboard cert
  - openssl genrsa -out /opt/wazuh/certs/dashboard.key 2048
  - openssl req -new -key /opt/wazuh/certs/dashboard.key -subj "/CN=dashboard" -out /opt/wazuh/certs/dashboard.csr
  - openssl x509 -req -in /opt/wazuh/certs/dashboard.csr -CA /opt/wazuh/certs/rootCA.crt -CAkey /opt/wazuh/certs/rootCA.key -CAcreateserial -out /opt/wazuh/certs/dashboard.crt -days 365 -sha256
#  - docker compose -f /opt/wazuh/docker-compose.yml up -d
