#cloud-config

hostname: wazuh
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - openssh-server
  - curl
  - wget
  - ca-certificates
  - docker.io

write_files:
  - path: /opt/wazuh/dashboard-config/opensearch_dashboards.yml
    owner: root:root
    permissions: '0644'
    content: |
      server.host: "0.0.0.0"
      server.port: 5601

      opensearch.hosts:
        - http://wazuh.indexer:9200
      
      opensearch.ssl.verificationMode: none
      
      opensearch_security.multitenancy.enabled: false


  - path: /opt/wazuh/docker-compose.yml
    owner: root:root
    permissions: '0644'
    content: |
        services:
          wazuh.indexer:
            image: wazuh/wazuh-indexer:4.14.1
            container_name: wazuh-indexer
            hostname: wazuh.indexer
            restart: always
            environment:
              - discovery.type=single-node
              - bootstrap.memory_lock=true
              - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
              - OPENSEARCH_SECURITY_DISABLED=true
            ulimits:
              memlock:
                soft: -1
                hard: -1
              nofile:
                soft: 65536
                hard: 65536
            ports:
              - "9200:9200"
            volumes:
              - wazuh-indexer-data:/var/lib/wazuh-indexer
        
        
          wazuh.manager:
            image: wazuh/wazuh-manager:4.14.1
            container_name: wazuh-manager
            hostname: wazuh.manager
            restart: always
            environment:
              - WAZUH_INDEXER_HOSTS=wazuh.indexer:9200
              - WAZUH_CLUSTER=disabled
            ports:
              - "1514:1514/udp"
              - "1515:1515"
              - "55000:55000"
            depends_on:
              - wazuh.indexer
            volumes:
              - wazuh_etc:/var/ossec/etc
              - wazuh_logs:/var/ossec/logs
              - wazuh_queue:/var/ossec/queue
              - wazuh_var:/var/ossec/var
              - wazuh_active_response:/var/ossec/active-response/bin
              - wazuh_wodles:/var/ossec/wodles
          
          wazuh.dashboard:
            image: wazuh/wazuh-dashboard:4.14.1
            container_name: wazuh-dashboard
            hostname: wazuh.dashboard
            restart: always
            environment:
              - SERVER_HOST=0.0.0.0
              - SERVER_PORT=5601
              - OPENSEARCH_HOSTS=http://wazuh.indexer:9200
              - DASHBOARD_USERNAME=admin
              - DASHBOARD_PASSWORD=admin
            ports:
              - "5601:5601"
            depends_on:
              - wazuh.indexer
              - wazuh.manager
            volumes:
              - /opt/wazuh/dashboard-config/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
        
        volumes:
          wazuh-indexer-data:
          wazuh_etc:
          wazuh_logs:
          wazuh_queue:
          wazuh_var:
          wazuh_active_response:
          wazuh_wodles:

    
runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable ssh --now
  - systemctl enable qemu-guest-agent
  - mkdir -p /opt/wazuh
  - cd /opt/wazuh
  - chown -R 1000:1000 /opt/wazuh/dashboard-config
#  - docker compose -f /opt/wazuh/docker-compose.yml up -d
