#cloud-config

hostname: wazuh
manage_etc_hosts: true

users:
  - name: wazuh
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: true
chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - curl

runcmd:
  - |
    nohup bash -c '
      echo "=== Installing Wazuh ==="

      curl -sO https://packages.wazuh.com/4.7/wazuh-install.sh

      bash wazuh-install.sh -a \
        -p "Password1!" \
        -n $(hostname -I | awk "{print \$1}")

      echo "=== Waiting for API ==="
      sleep 120

      echo "=== Creating wazuh user ==="

      cat <<EOF > /tmp/wazuh-user.json
      {
        "username": "wazuh",
        "password": "Password1!",
        "roles": ["administrator"]
      }
      EOF

      curl -k -u admin:Password1! \
        -X POST "https://localhost:55000/security/users" \
        -H "Content-Type: application/json" \
        -d @/tmp/wazuh-user.json

      echo "=== Done ==="
      ' > /root/wazuh-install.log 2>&1 &
  
power_state:
  mode: poweroff
  message: "Cloud-init finished - powering off"
  timeout: 30
  condition: True
