#cloud-config

hostname: wazuh
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - openssh-server
  - curl
  - wget
  - ca-certificates
  - docker.io

write_files:
  - path: /opt/wazuh/docker-compose.yml
    owner: root:root
    permissions: '0644'
    content: |
         version: "3.9"
            services:
              wazuh.manager:
                image: wazuh/wazuh-manager:4.14.1
                hostname: wazuh.manager
                restart: always
                ports:
                  - "1514:1514"
                  - "1515:1515"
                  - "55000:55000"
                environment:
                  - WAZUH_INDEXER_HOSTS=wazuh.indexer:9200
                  - WAZUH_NODE_NAME=manager
                  - WAZUH_CLUSTER_NODES=wazuh.manager
                  - WAZUH_CLUSTER_BIND_ADDR=wazuh.manager
                  - INDEXER_USERNAME=admin
                  - INDEXER_PASSWORD=admin
                  - API_USERNAME=wazuh-wui
                  - API_PASSWORD=MyS3cr37P450r.*-
                ulimits:
                  memlock:
                    soft: -1
                    hard: -1
                  nofile:
                    soft: 655360
                    hard: 655360
                volumes:
                  - wazuh_api_configuration:/var/ossec/api/configuration
                  - wazuh_etc:/var/ossec/etc
                  - wazuh_logs:/var/ossec/logs
                  - wazuh_queue:/var/ossec/queue
                  - wazuh_var_multigroups:/var/ossec/var/multigroups
                  - wazuh_active_response:/var/ossec/active-response/bin
                  - wazuh_wodles:/var/ossec/wodles
                  - ./wazuh-certificates:/var/ossec/etc/certs
            
              wazuh.indexer:
                image: wazuh/wazuh-indexer:4.14.1
                hostname: wazuh.indexer
                restart: always
                ports:
                  - "9200:9200"
                environment:
                  - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
                  - bootstrap.memory_lock=true
                  - network.host=wazuh.indexer
                  - node.name=wazuh.indexer
                  - cluster.initial_cluster_manager_nodes=wazuh.indexer
                  - node.max_local_storage_nodes=1
                  - plugins.security.allow_default_init_securityindex=true
                  - NODES_DN=CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California,C=US
                ulimits:
                  memlock:
                    soft: -1
                    hard: -1
                  nofile:
                    soft: 65536
                    hard: 65536
                volumes:
                  - wazuh-indexer-data:/var/lib/wazuh-indexer
                  - ./wazuh-certificates:/usr/share/wazuh-indexer/config/certs
            
              wazuh.dashboard:
                image: wazuh/wazuh-dashboard:4.14.1
                hostname: wazuh.dashboard
                restart: always
                depends_on:
                  - wazuh.indexer
                  - wazuh.manager
                ports:
                  - "443:443"
                environment:
                  - SERVER_HOST=0.0.0.0
                  - OPENSEARCH_HOSTS=https://wazuh.indexer:9200
                  - INDEXER_USERNAME=admin
                  - INDEXER_PASSWORD=admin
                  - WAZUH_API_URL=https://wazuh.manager
                  - DASHBOARD_USERNAME=kibanaserver
                  - DASHBOARD_PASSWORD=kibanaserver
                  - API_USERNAME=wazuh-wui
                  - API_PASSWORD=MyS3cr37P450r.*-
                  - SERVER_SSL_CERTIFICATE=/usr/share/wazuh-dashboard/config/certs/wazuh.dashboard.pem
                  - SERVER_SSL_KEY=/usr/share/wazuh-dashboard/config/certs/wazuh.dashboard-key.pem
                  - OPENSEARCH_SSL_CERTIFICATE_AUTHORITIES=/usr/share/wazuh-dashboard/config/certs/root-ca.pem
                volumes:
                  - ./wazuh-certificates:/usr/share/wazuh-dashboard/config/certs
                  - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
            
            volumes:
              wazuh_api_configuration:
              wazuh_etc:
              wazuh_logs:
              wazuh_queue:
              wazuh_var_multigroups:
              wazuh_active_response:
              wazuh_wodles:
              wazuh-indexer-data:
              wazuh-dashboard-custom:
            
            

runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable ssh --now
  - systemctl enable qemu-guest-agent
  - mkdir -p /opt/wazuh
  - cd /opt/wazuh
#  - docker compose -f /opt/wazuh/docker-compose.yml up -d
