#cloud-config
hostname: wazuh
manage_etc_hosts: true

users:
  - name: ec2-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys: []
ssh_pwauth: false

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - 192.168.2.20/24
      gateway4: 192.168.20.1
    eth1:
      dhcp4: false
      addresses:
        - 172.20.0.20/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.20.1
nameservers:
  addresses: [1.1.1.1, 8.8.8.8]

runcmd:
  - systemctl enable wazuh-manager || true
  - systemctl restart wazuh-manager || true
