#cloud-config

hostname: wazuh
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - openssh-server
  - curl
  - wget
  - ca-certificates
  - docker.io

write_files:
  - path: /opt/wazuh/dashboard-config/opensearch_dashboards.yml
    owner: root:root
    permissions: '0644'
    content: |
      server.host: "0.0.0.0"
      server.port: 5601
      
      # Indexer uses HTTPS now
      opensearch.hosts:
        - https://wazuh.indexer:9200
      
      # Trust your custom CA
      opensearch.ssl.certificateAuthorities: /usr/share/wazuh-dashboard/config/certs/root-ca.pem
      
      # Don't require mutual TLS (dashboard has its own cert already)
      opensearch.ssl.verificationMode: full
      
      # Wazuh / OpenSearch Dashboards features
      opensearch_security.multitenancy.enabled: true
      opensearch_security.readonly_mode.roles: ["kibana_read_only"]
      opensearch_security.cookie.secure: true

  - path: /opt/wazuh/docker-compose.yml
    owner: root:root
    permissions: '0644'
    content: |
      services:
        wazuh.manager:
          image: wazuh/wazuh-manager:4.14.1
          hostname: wazuh.manager
          container_name: single-node-wazuh.manager
          restart: always
          ulimits:
            memlock:
              soft: -1
              hard: -1
            nofile:
              soft: 655360
              hard: 655360
          ports:
            - "1514:1514"
            - "1515:1515"
            - "514:514/udp"
            - "55000:55000"
          environment:
            - WAZUH_INDEXER_HOSTS=wazuh.indexer:9200
            - WAZUH_NODE_NAME=manager
            - WAZUH_CLUSTER_NODES=wazuh.manager
            - WAZUH_CLUSTER_BIND_ADDR=wazuh.manager
            - INDEXER_USERNAME=admin
            - INDEXER_PASSWORD=admin
            - API_USERNAME=wazuh-wui
            - API_PASSWORD=MyS3cr37P450r.*-
          volumes:
            - wazuh_api_configuration:/var/ossec/api/configuration
            - wazuh_etc:/var/ossec/etc
            - wazuh_logs:/var/ossec/logs
            - wazuh_queue:/var/ossec/queue
            - wazuh_var_multigroups:/var/ossec/var/multigroups
            - wazuh_active_response:/var/ossec/active-response/bin
            - wazuh_wodles:/var/ossec/wodles
            - ./wazuh-certificates/root-ca.pem:/var/ossec/etc/certs/root-ca.pem
            - ./wazuh-certificates/wazuh.manager.pem:/var/ossec/etc/certs/server.pem
            - ./wazuh-certificates/wazuh.manager-key.pem:/var/ossec/etc/certs/server-key.pem
      
        wazuh.indexer:
          image: wazuh/wazuh-indexer:4.14.1
          hostname: wazuh.indexer
          container_name: single-node-wazuh.indexer
          restart: always
          ports:
            - "9200:9200"
          environment:
            - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
            - bootstrap.memory_lock=true
            - network.host=wazuh.indexer
            - node.name=wazuh.indexer
            - cluster.initial_cluster_manager_nodes=wazuh.indexer
            - node.max_local_storage_nodes=1
            - plugins.security.allow_default_init_securityindex=true
            - NODES_DN=CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California,C=US
          ulimits:
            memlock:
              soft: -1
              hard: -1
            nofile:
              soft: 65536
              hard: 65536
          volumes:
            - wazuh-indexer-data:/var/lib/wazuh-indexer
            - /opt/wazuh/certs/rootCA.crt:/usr/share/wazuh-indexer/config/certs/root-ca.pem
            - /opt/wazuh/certs/indexer.key:/usr/share/wazuh-indexer/config/certs/indexer-key.pem
            - /opt/wazuh/certs/indexer.crt:/usr/share/wazuh-indexer/config/certs/indexer.pem
            - /opt/wazuh/certs/indexer.crt:/usr/share/wazuh-indexer/config/certs/admin.pem
            - /opt/wazuh/certs/indexer.key:/usr/share/wazuh-indexer/config/certs/admin-key.pem
      
        wazuh.dashboard:
          image: wazuh/wazuh-dashboard:4.14.1
          hostname: wazuh.dashboard
          container_name: single-node-wazuh.dashboard
          restart: always
          ports:
            - 443:5601
          environment:
            - SERVER_PORT=5601
            - SERVER_HOST=0.0.0.0
            - OPENSEARCH_HOSTS=https://wazuh.indexer:9200
            - INDEXER_USERNAME=admin
            - INDEXER_PASSWORD=admin
            - WAZUH_API_URL=https://wazuh.manager
            - DASHBOARD_USERNAME=kibanaserver
            - DASHBOARD_PASSWORD=kibanaserver
            - API_USERNAME=wazuh-wui
            - API_PASSWORD=MyS3cr37P450r.*-
            - SERVER_SSL_CERTIFICATE=/usr/share/wazuh-dashboard/config/certs/dashboard.pem
            - SERVER_SSL_KEY=/usr/share/wazuh-dashboard/config/certs/dashboard-key.pem
            - OPENSEARCH_SSL_CERTIFICATE_AUTHORITIES=/usr/share/wazuh-dashboard/config/certs/root-ca.pem
          volumes:
            - /opt/wazuh/certs/dashboard.crt:/usr/share/wazuh-dashboard/config/certs/dashboard.pem
            - /opt/wazuh/certs/dashboard.key:/usr/share/wazuh-dashboard/config/certs/dashboard-key.pem
            - /opt/wazuh/certs/rootCA.crt:/usr/share/wazuh-dashboard/config/certs/root-ca.pem
            - /opt/wazuh/dashboard-config:/usr/share/wazuh-dashboard/config
            - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
          depends_on:
            - wazuh.indexer
          links:
            - wazuh.indexer:wazuh.indexer
            - wazuh.manager:wazuh.manager
      
      volumes:
        wazuh_api_configuration:
        wazuh_etc:
        wazuh_logs:
        wazuh_queue:
        wazuh_var_multigroups:
        wazuh_active_response:
        wazuh_wodles:
        wazuh-indexer-data:
        wazuh-dashboard-config:
        wazuh-dashboard-custom:
      

runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable ssh --now
  - systemctl enable qemu-guest-agent
  - mkdir -p /opt/wazuh
  - mkdir -p /opt/wazuh/certs
  - cd /opt/wazuh
  - chown -R 1000:1000 /opt/wazuh/dashboard-config
  - |
      # Generate certs in the background so cloud-init does not hang
      bash -c '
      set -e

      # Root CA (2048 instead of 4096 for speed in labs)
      openssl genrsa -out /opt/wazuh/certs/rootCA.key 2048
      openssl req -x509 -new -nodes -key /opt/wazuh/certs/rootCA.key -sha256 -days 3650 \
        -subj "/CN=wazuh-rootCA" -out /opt/wazuh/certs/rootCA.crt

      # Indexer cert
      openssl genrsa -out /opt/wazuh/certs/indexer.key 2048
      openssl req -new -key /opt/wazuh/certs/indexer.key -subj "/CN=wazuh.indexer" -out /opt/wazuh/certs/indexer.csr
      openssl x509 -req -in /opt/wazuh/certs/indexer.csr -CA /opt/wazuh/certs/rootCA.crt -CAkey /opt/wazuh/certs/rootCA.key \
        -CAcreateserial -out /opt/wazuh/certs/indexer.crt -days 365 -sha256

      # Manager cert
      openssl genrsa -out /opt/wazuh/certs/manager.key 2048
      openssl req -new -key /opt/wazuh/certs/manager.key -subj "/CN=wazuh.manager" -out /opt/wazuh/certs/manager.csr
      openssl x509 -req -in /opt/wazuh/certs/manager.csr -CA /opt/wazuh/certs/rootCA.crt -CAkey /opt/wazuh/certs/rootCA.key \
        -CAcreateserial -out /opt/wazuh/certs/manager.crt -days 365 -sha256

      # Dashboard cert
      openssl genrsa -out /opt/wazuh/certs/dashboard.key 2048
      openssl req -new -key /opt/wazuh/certs/dashboard.key -subj "/CN=wazuh.dashboard" -out /opt/wazuh/certs/dashboard.csr
      openssl x509 -req -in /opt/wazuh/certs/dashboard.csr -CA /opt/wazuh/certs/rootCA.crt -CAkey /opt/wazuh/certs/rootCA.key \
        -CAcreateserial -out /opt/wazuh/certs/dashboard.crt -days 365 -sha256

      chown -R 1000:1000 /opt/wazuh/certs  ' &
#  - docker compose -f /opt/wazuh/docker-compose.yml up -d
