#cloud-config

hostname: appsrv01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

write_files:

  - path: /opt/radius/docker-compose.yml
    permissions: "0644"
    content: |
      version: "3.8"

      services:

        ldap:
          image: osixia/openldap:1.5.0
          container_name: ldap
          restart: always
          environment:
            LDAP_ORGANISATION: "MyCompany"
            LDAP_DOMAIN: "mycompany.local"
            LDAP_ADMIN_PASSWORD: "Password1!"
            LDAP_TLS: "false"
          volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d
          ports:
            - "389:389"

        ldapadmin:
          image: osixia/phpldapadmin:0.9.0
          container_name: phpldapadmin
          restart: always
          environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
            PHPLDAPADMIN_HTTPS: "false"
          ports:
            - "8082:80"
          depends_on:
            - ldap

        mariadb:
          image: mariadb:11
          container_name: rd-db
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: rd
            MYSQL_USER: rd
            MYSQL_PASSWORD: rdpass
          volumes:
            - db_data:/var/lib/mysql

        radiusdesk:
          image: radiusdesk/radiusdesk:latest
          container_name: radiusdesk
          restart: always
          depends_on:
            - mariadb
            - ldap
          ports:
            - "1812:1812/udp"
            - "1813:1813/udp"
            - "8080:80"
          environment:
            RD_DB_HOST: mariadb
            RD_DB_NAME: rd
            RD_DB_USER: rd
            RD_DB_PASS: rdpass

      volumes:
        db_data:
        ldap_data:
        ldap_config:

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable docker
  - systemctl start docker

  - mkdir -p /usr/local/lib/docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

  - mkdir -p /opt/radius
  - cd /opt/radius && docker compose up -d

final_message: |
  Identity Platform Installed

  RadiusDesk (RADIUS GUI):
  http://SERVER_IP:8080
  Login: root / admin

  LDAP GUI:
  http://SERVER_IP:8082
  Login DN: cn=admin,dc=mycompany,dc=local
  Password: Password1!
