#cloud-config

hostname: appsrv01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

write_files:

  # Docker Compose
  - path: /opt/radius/docker-compose.yml
    permissions: "0644"
    content: |
      version: "3.8"

      services:

        mariadb:
          image: mariadb:11
          container_name: rd-db
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: rd
            MYSQL_USER: rd
            MYSQL_PASSWORD: rdpass
          volumes:
            - db_data:/var/lib/mysql

        ldap:
          image: osixia/openldap:1.5.0
          container_name: ldap
          restart: always
          environment:
            LDAP_ORGANISATION: "MyCompany"
            LDAP_DOMAIN: "mycompany.local"
            LDAP_ADMIN_PASSWORD: "Password1!"
            LDAP_TLS: "false"
          volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d
          ports:
            - "389:389"

        ldapadmin:
          image: osixia/phpldapadmin:0.9.0
          container_name: phpldapadmin
          restart: always
          environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
            PHPLDAPADMIN_HTTPS: "false"
          ports:
            - "8082:80"
          depends_on:
            - ldap

        freeradius:
          image: freeradius/freeradius-server:3.2
          container_name: freeradius
          restart: always
          depends_on:
            - mariadb
            - ldap
          ports:
            - "1812:1812/udp"
            - "1813:1813/udp"
          volumes:
            - radius_conf:/etc/freeradius

        radiusdesk:
          build: ./radiusdesk
          container_name: radiusdesk
          restart: always
          depends_on:
            - mariadb
            - freeradius
          ports:
            - "8080:80"

      volumes:
        db_data:
        ldap_data:
        ldap_config:
        radius_conf:

  # RadiusDesk Dockerfile
  - path: /opt/radius/radiusdesk/Dockerfile
    permissions: "0644"
    content: |
      FROM php:8.2-apache

      RUN apt update && apt install -y \
        git mariadb-client unzip libpng-dev libjpeg-dev \
        libonig-dev libxml2-dev curl && \
        docker-php-ext-install mysqli pdo pdo_mysql gd

      WORKDIR /var/www/html

      RUN git clone https://github.com/RADIUSdesk/radiusdesk.git . \
          && chown -R www-data:www-data .

      EXPOSE 80

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable docker
  - systemctl start docker

  - mkdir -p /usr/local/lib/docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

  - cd /opt/radius && docker compose build
  - cd /opt/radius && docker compose up -d

final_message: |
  Identity system deployed

  RadiusDesk GUI:
  http://SERVER_IP:8080

  LDAP GUI:
  http://SERVER_IP:8082

  LDAP admin:
  cn=admin,dc=mycompany,dc=local
  Password1!
