#cloud-config

hostname: appsrv01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - docker.io

write_files:
  - path: /etc/sysctl.d/99-mirror.conf
    permissions: "0644"
    content: |
         net.ipv4.ip_forward=0
      
  - path: /etc/systemd/system/mirror-ens20.service
    permissions: "0644"
    content: |
      [Unit]
      After=network.target

      [Service]
      Type=oneshot
      ExecStart=/sbin/ip addr flush dev ens20
      ExecStart=/sbin/ip link set ens20 up
      ExecStart=/sbin/ethtool -K ens20 tx off rx off tso off gso off gro off lro off

      [Install]
      WantedBy=multi-user.target
      
runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - systemctl enable mirror-eth2.service
  - usermod -aG docker ubuntu
  - mkdir -p /opt/suricata
  - wget -O /opt/suricata/docker-compose.yml https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/SURICATA/docker-compose.yml
  - mkdir -p /opt/suricata/suricata
  - wget -O /opt/suricata/suricata/suricata.yaml https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/SURICATA/suricata/suricata.yaml
  - wget -O /opt/suricata/suricata/suricata.rules https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/SURICATA/suricata/suricata.rules
  - mkdir -p /opt/radius
  - mkdir -p /opt/radius/freeradius
  - mkdir -p /opt/radius/freeradius/mods-enabled
  - mkdir -p /opt/radius/freeradius/sites-enabled
  - mkdir -p /opt/radius/ldap
  - wget -O /opt/radius/docker-compose.yml https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/RADIUS/docker-compose.yml
  - wget -O /opt/radius/freeradius/clients.conf https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/RADIUS/freeradius/clients.conf
  - wget -O /opt/radius/freeradius/mods-enabled/ldap https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/RADIUS/freeradius/mods-enabled/ldap
  - wget -O /opt/radius/freeradius/sites-enabled/default https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/RADIUS/freeradius/sites-enabled/default
  - wget -O /opt/radius/ldap/01-ou.ldif https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/RADIUS/ldap/01-ou.ldif
  - wget -O /opt/radius/ldap/02-users.ldif https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/DOCKERFILES/RADIUS/ldap/02-users.ldif
  - chown -R ubuntu:ubuntu /opt

power_state:
  mode: reboot
  message: "Reboot after initial cloud-init setup"
  timeout: 30
  condition: true
