#cloud-config

hostname: appsrv01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

write_files:

  - path: /opt/radius/docker-compose.yml
    permissions: "0644"
    content: |
      services:

        ldap:
          image: osixia/openldap:1.5.0
          container_name: ldap
          restart: always
          environment:
            LDAP_ORGANISATION: "MyCompany"
            LDAP_DOMAIN: "mycompany.local"
            LDAP_ADMIN_PASSWORD: "StrongAdminPass123"
            LDAP_TLS: "false"
          volumes:
            - ldap_data:/var/lib/ldap
            - ldap_config:/etc/ldap/slapd.d
          ports:
            - "389:389"

        ldapadmin:
          image: osixia/phpldapadmin:0.9.0
          container_name: phpldapadmin
          restart: always
          environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
            PHPLDAPADMIN_HTTPS: "false"
          ports:
            - "8082:80"
          depends_on:
            - ldap

        mariadb:
          image: mariadb:11
          container_name: radius-db
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: radius
            MYSQL_USER: radius
            MYSQL_PASSWORD: radiuspass
          volumes:
            - db_data:/var/lib/mysql

        freeradius:
          image: freeradius/freeradius-server:3.2
          container_name: freeradius
          restart: always
          depends_on:
            - mariadb
            - ldap
          ports:
            - "1812:1812/udp"
            - "1813:1813/udp"
          volumes:
            - freeradius_conf:/etc/freeradius

        daloradius:
          image: henning/daloradius:latest
          container_name: daloradius
          restart: always
          depends_on:
            - mariadb
          ports:
            - "8080:80"
          environment:
            DB_HOST: mariadb
            DB_NAME: radius
            DB_USER: radius
            DB_PASSWORD: radiuspass

      volumes:
        db_data:
        freeradius_conf:
        ldap_data:
        ldap_config:

  - path: /opt/radius/freeradius/mods-enabled/ldap
    permissions: "0644"
    content: |
      ldap {
        server = "ldap"
        port = 389
        identity = "cn=admin,dc=mycompany,dc=local"
        password = "Password1!"
        base_dn = "dc=mycompany,dc=local"

        user {
          base_dn = "ou=users,dc=mycompany,dc=local"
          filter = "(uid=%{%{Stripped-User-Name}:-%{User-Name}})"
        }

        group {
          base_dn = "ou=groups,dc=mycompany,dc=local"
          filter = "(memberUid=%{User-Name})"
        }
      }

runcmd:
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable docker
  - systemctl start docker

  - mkdir -p /usr/local/lib/docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

  - mkdir -p /opt/radius/freeradius/mods-enabled
  - cd /opt/radius && docker compose up -d

  - sleep 30

  # Initialize daloRADIUS DB
  - docker exec radius-db mysql -uradius -pradiuspass radius < /usr/share/daloradius/contrib/db/mysql-daloradius.sql
  - docker exec radius-db mysql -uradius -pradiuspass radius < /usr/share/daloradius/contrib/db/fr2-mysql-daloradius-and-freeradius.sql

final_message: |
  Full Identity Platform installed.

  RADIUS GUI:
  http://SERVER_IP:8080
  Login: administrator / radius

  LDAP GUI:
  http://SERVER_IP:8082
  Login DN: cn=admin,dc=mycompany,dc=local
  Password: Password1!
