#cloud-config

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
   
chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - ca-certificates
  - curl
  - docker.io
  
runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2
  - mkdir -p /home/ubuntu/.ssh
  - curl -fsSL https://github.com/EUD-cyber/eud-cyber/main/SSHKEYS/shared_admin_ed25519.pub >> /home/ubuntu/.ssh/authorized_keys
  - chown -R ubuntu:ubuntu /home/ubuntu/.ssh
  - chmod 700 /home/ubuntu/.ssh
  - chmod 600 /home/ubuntu/.ssh/authorized_keys
  
  # Enable Docker
  - systemctl enable docker
  - systemctl start docker

  # Create working directory
  - mkdir -p /opt/guacamole
  - cd /opt/guacamole

  # Start services
#  - docker compose -f /opt/guacamole/docker-compose.yml up -d
