#cloud-config

hostname: guacvm
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key
   
chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - ca-certificates
  - curl
  - docker.io

write_files:
  - path: /opt/guacamole/docker-compose.yml
    owner: root:root
    permissions: '0644'
    content: |
        networks:
          guacnetwork_compose:
            driver: bridge        
        # services
        services:
          # guacd
          guacd:
            container_name: guacd_compose
            image: guacamole/guacd:1.6.0
            networks:
              - guacnetwork_compose
            restart: always
            volumes:
            - ./drive:/drive:rw
            - ./record:/record:rw
          # postgres
          postgres:
            container_name: postgres_guacamole_compose
            environment:
              PGDATA: /var/lib/postgresql/data/guacamole
              POSTGRES_DB: guacamole_db
              POSTGRES_PASSWORD: 'Password1!'
              POSTGRES_USER: guacamole_user
            image: postgres:15.2-alpine
            networks:
              - guacnetwork_compose
            restart: always
            volumes:
            - ./init:/docker-entrypoint-initdb.d:z
            - ./data:/var/lib/postgresql/data:Z        
          # guacamole
          guacamole:
            container_name: guacamole_compose
            group_add:
              - "1000"
            depends_on:
            - guacd
            - postgres
            environment:
              GUACD_HOSTNAME: guacd
              POSTGRESQL_DATABASE: guacamole_db
              POSTGRESQL_HOSTNAME: postgres
              POSTGRESQL_PASSWORD: 'Password1!'
              POSTGRESQL_USERNAME: guacamole_user
              RECORDING_SEARCH_PATH: /record
            image: guacamole/guacamole:1.6.0
            networks:
              - guacnetwork_compose
            volumes:
              - ./record:/record:rw
            ports:
              - 8080:8080/tcp
            restart: always        
          nginx:
            image: nginx:alpine
            container_name: guac-nginx
            ports:
            - "80:80"
            volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/web:/var/www/html:ro
            depends_on:
            - guacamole
            networks:
            - guacnetwork_compose
            
  - path: /opt/guacamole/nginx/web/index.html
    owner: root:root
    permissions: '0644'
    content: | 

        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8" />
        <title>Lab Portal</title>
        
        <style>
          body {
            font-family: Arial, sans-serif;
            background: #0f172a;
            color: #e5e7eb;
            padding: 30px;
          }
        
          .headline {
            font-size: 28px;
            font-weight: bold;
            margin-bottom: 20px;
          }
        
          h1 { margin-bottom: 25px; }
        
          .layout {
            display: grid;
            grid-template-columns: 280px 1fr;
            gap: 30px;
          }
        
          .panel {
            background: #111827;
            border: 1px solid #1f2937;
            border-radius: 10px;
            padding: 16px;
          }
        
          .panel h2 {
            margin-top: 0;
            font-size: 18px;
            margin-bottom: 14px;
          }
        
          .button {
            display: block;
            width: 100%;
            text-align: center;
            margin-bottom: 10px;
            padding: 10px 14px;
            background: #2563eb;
            color: white;
            border-radius: 6px;
            text-decoration: none;
            font-size: 14px;
          }
        
          .button:hover { background: #1d4ed8; }
        
          .right-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
          }
        
          .right-card {
            background: #0b1220;
            border: 1px solid #1f2937;
            border-radius: 10px;
            padding: 14px;
            min-height: 140px;
          }
        
          .right-card h3 {
            margin: 0 0 10px;
            font-size: 15px;
            color: #cbd5e1;
          }
        </style>
        
        <script>
          const HOST = window.location.hostname;
          function link(path="") {
            return `http://${HOST}${path}`;
          }
        </script>
        </head>
        
        <body>
        
        <div class="headline">Cyber sikkerheds labs</div>
        
        <h1>Lab Portal</h1>
        
        <div class="layout">
        
          <!-- LEFT: GUAC CONNECTIONS -->
          <div class="panel">
            <h2>Connections</h2>
        
            <a class="button"
               target="_blank"
               href="#"
               onclick="this.href = link('/guacamole/#/client/NwBjAHBvc3RncmVzcWw');">
               OPNsense SSH
            </a>
        
            <a class="button"
               target="_blank"
               href="#"
               onclick="this.href = link('/guacamole/#/client/NABjAHBvc3RncmVzcWw');">
               Wazuh SSH
            </a>
        
            <a class="button"
               target="_blank"
               href="#"
               onclick="this.href = link('/guacamole/#/client/NgBjAHBvc3RncmVzcWw');">
               Kali01 VNC
            </a>
        
            <a class="button"
               target="_blank"
               href="#"
               onclick="this.href = link('/guacamole/#/client/MgBjAHBvc3RncmVzcWw');">
               Kali01 SSH
            </a>
          </div>
        
          <!-- RIGHT: 4 COLUMNS WITH BUTTONS -->
          <div class="panel">
            <h2>Sections</h2>
        
            <div class="right-grid">
        
              <div class="right-card">
                <h3>Network</h3>
                <a class="button" href="#">Button 1</a>
                <a class="button" href="#">Button 2</a>
              </div>
        
              <div class="right-card">
                <h3>Application</h3>
                <a class="button" href="#">Button 1</a>
                <a class="button" href="#">Button 2</a>
              </div>
        
              <div class="right-card">
                <h3>Data</h3>
                <a class="button" href="#">Button 1</a>
                <a class="button" href="#">Button 2</a>
              </div>
        
              <div class="right-card">
                <h3>Other</h3>
                <a class="button" href="#">Button 1</a>
                <a class="button" href="#">Button 2</a>
              </div>
        
            </div>
          </div>
        
        </div>
        
        </body>
        </html>

  - path: /opt/guacamole/nginx/nginx.conf
    owner: root:root
    permissions: '0644'
    content: | 
      server {
                listen 80;
                server_name _;
            
                # ---- Static Frontend ----
                location / {
                    root /var/www/html;
                    index index.html;
                    try_files $uri $uri/ =404;
                }
            
                # ---- Guacamole ----
                location /guacamole/ {
                    proxy_pass http://guacamole:8080/guacamole/;
                    proxy_http_version 1.1;
            
                    proxy_buffering off;
            
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
            
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection $http_connection;
            
                    proxy_cookie_path /guacamole/ /guacamole/;
                }
            }


runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable qemu-guest-agent
  - mkdir -p /opt/guacamole
  - cd /opt/guacamole
  - mkdir ./init >/dev/null 2>&1
  - mkdir -p ./nginx >/dev/null 2>&1
  - mkdir /opt/guacamole/nginx/web
  - chmod -R +x ./init
  - wget -O /opt/guacamole/guacamole.sql.gz https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/GUACVM/guacamole.sql.gz
  - docker run --rm 'guacamole/guacamole:1.6.0' /opt/guacamole/bin/initdb.sh --postgresql > ./init/initdb.sql
  - gunzip -c /opt/guacamole/guacamole.sql.gz > ./init/02-restore.sql
  - mkdir ./record >/dev/null 2>&1
  - chmod -R 777 ./record
  - docker compose -f /opt/guacamole/docker-compose.yml up -d
