#cloud-config

hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - ubuntu-desktop-minimal
  - gnome-remote-desktop
  - qemu-guest-agent

runcmd:
  - set -x
  - apt-get update
  - apt-get install -y ubuntu-desktop-minimal gnome-remote-desktop qemu-guest-agent
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - systemctl set-default graphical.target
  - systemctl enable gdm3
  - |
    sed -i 's/^#  AutomaticLoginEnable = true/AutomaticLoginEnable = true/' /etc/gdm3/custom.conf
    sed -i 's/^#  AutomaticLogin = ubuntu/AutomaticLogin = ubuntu/' /etc/gdm3/custom.conf
  - reboot

