#cloud-config

hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: true
disable_root: true

chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - ubuntu-desktop
  - xrdp
  - xorgxrdp
  - openssh-server
  - qemu-guest-agent

write_files:
  - path: /etc/gdm3/custom.conf
    permissions: "0644"
    content: |
      [daemon]
      WaylandEnable=false
      AutomaticLoginEnable=false

runcmd:
  - set -x
  - export DEBIAN_FRONTEND=noninteractive

  # Enable required services
  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

  # Force graphical boot
  - systemctl set-default graphical.target
  - systemctl enable gdm3

  # Enable XRDP
  - systemctl enable xrdp
  - systemctl restart xrdp

  # Allow XRDP to access SSL cert
  - adduser xrdp ssl-cert

  - reboot
