#cloud-config

hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

packages:
  - xfce4
  - xfce4-goodies
  - xfce4-session
  - dbus-x11
  - openssh-server
  - tigervnc-standalone-server
  - tigervnc-common
  - curl
  - qemu-guest-agent

write_files:
  - path: /home/ubuntu/.vnc/xstartup
    owner: root:root
    permissions: "0755"
    content: |
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec dbus-launch --exit-with-session startxfce4 &

  - path: /etc/systemd/system/vncserver.service
    permissions: "0644"
    content: |
      [Unit]
      Description=TigerVNC server on display :1
      After=network.target
      
      [Service]
      Type=simple
      User=ubuntu
      WorkingDirectory=/home/ubuntu
      
      # Kill any stale VNC session first
      ExecStartPre=/usr/bin/vncserver -kill :1 || true
      
      # Run in foreground so systemd can track it
      ExecStart=/usr/bin/vncserver -localhost=no -geometry 1280x720 -fg :1
      
      Restart=on-failure
      RestartSec=5
      
      [Install]
      WantedBy=multi-user.target


runcmd:
  - set -x
  - export DEBIAN_FRONTEND=noninteractive

  # Ensure SSH + agent
  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

  # Create VNC directories
  - mkdir -p /home/ubuntu/.vnc
  - mkdir -p /home/ubuntu/.config/tigervnc
  - chown -R ubuntu:ubuntu /home/ubuntu

  # Boot headless (no console desktop)
  - systemctl set-default multi-user.target

  # Set VNC password
  - su - ubuntu -c "printf 'password\npassword\n\n' | vncpasswd"

  # Enable VNC service
  - systemctl daemon-reload
  - systemctl enable vncserver
  - systemctl start vncserver

  - reboot
