#cloud-config

hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: true
disable_root: true

chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - ubuntu-desktop
  - xrdp
  - gnome-flashback
  - metacity
  - dbus-x11
  - openssh-server
  - qemu-guest-agent
  - gnome-panel metacity


write_files:
  - path: /home/ubuntu/.xsession
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/sh
      gsettings set org.gnome.gnome-flashback.desktop show-desktop-icons true
      exec gnome-session --session=gnome-flashback-metacity
  

runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - chown -R ubuntu:ubuntu /home/ubuntu/.xsession
  - systemctl daemon-reload
  - systemctl enable xrdp
  - systemctl restart xrdp

#power_state:
#  mode: reboot
#  message: "Reboot after cloud-init setup"
#  timeout: 30
#  condition: true
