#cloud-config

hostname: client01
manage_etc_hosts: true

network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - 192.168.1.120/24
      gateway4: 192.168.1.1
      nameservers:
        addresses:
          - 8.8.8.8
    eth1:
      dhcp4: false
      addresses:
        - 172.20.0.15/24

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: true
disable_root: true

chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - xfce4
  - xfce4-goodies
  - xrdp
  - xorgxrdp
  - network-manager
  - openssh-server
  - qemu-guest-agent

write_files:
  # Tell XRDP to start XFCE (CRITICAL)
  - path: /home/ubuntu/.xsession
    owner: ubuntu:ubuntu
    permissions: "0644"
    content: |
      startxfce4

runcmd:
  - export DEBIAN_FRONTEND=noninteractive

  # Enable base services
  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

  # XRDP setup
  - adduser xrdp ssl-cert
  - systemctl enable xrdp
  - systemctl restart xrdp

  # Ensure correct ownership
  - chown ubuntu:ubuntu /home/ubuntu/.xsession

  # Reboot after install
  - sleep 10
  - reboot
