#cloud-config
hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: false
disable_root: true

package_update: true
package_upgrade: true

packages:
  - ubuntu-desktop-minimal
  - gdm3
  - x11vnc
  - openssh-server
  - qemu-guest-agent

write_files:
  - path: /etc/systemd/system/x11vnc.service
    permissions: "0644"
    content: |
      [Unit]
      Description=x11vnc server for GNOME
      After=display-manager.service
      Requires=display-manager.service

      [Service]
      Type=simple
      ExecStart=/usr/bin/x11vnc -display :0 -auth guess -forever -shared -rfbport 5900
      Restart=always

      [Install]
      WantedBy=graphical.target

runcmd:
  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

  # GNOME must boot
  - systemctl set-default graphical.target
  - systemctl enable gdm3

  # Set x11vnc password (non-interactive)
  - x11vnc -storepasswd password /etc/x11vnc.pass
  - sed -i 's|ExecStart=.*|ExecStart=/usr/bin/x11vnc -display :0 -auth guess -rfbauth /etc/x11vnc.pass -forever -shared -rfbport 5900|' /etc/systemd/system/x11vnc.service

  - systemctl daemon-reload
  - systemctl enable x11vnc
  - systemctl start x11vnc

  - reboot
