#cloud-config

hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: true
disable_root: true

chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - lxqt
  - dbus-x11
  - xrdp
  - xorgxrdp
  - network-manager
  - openssh-server
  - qemu-guest-agent

write_files:
  # XRDP session startup (no display manager)
  - path: /home/ubuntu/.xsession
    owner: root:root
    permissions: "0755"
    content: |
      exec dbus-launch --exit-with-session startlxqt

  # Force XRDP WM startup
  - path: /etc/xrdp/startwm.sh
    permissions: "0755"
    content: |
      #!/bin/sh
      unset DBUS_SESSION_BUS_ADDRESS
      unset XDG_RUNTIME_DIR
      exec dbus-launch --exit-with-session startlxqt

runcmd:
  - export DEBIAN_FRONTEND=noninteractive

  # Base services
  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

  # XRDP
  - adduser xrdp ssl-cert
  - systemctl enable xrdp
  - systemctl restart xrdp
  - systemctl restart xrdp-sesman

  # Safety ownership fix
  - chown ubuntu:ubuntu /home/ubuntu/.xsession
  
  # Reboot once
  - sleep 10
  - reboot
