#cloud-config

hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: true
disable_root: true

chpasswd:
  expire: false

power_state:
  mode: reboot
  message: "Reboot after cloud-init setup"
  timeout: 30
  condition: true

package_update: true
package_upgrade: true

packages:
  - tigervnc-standalone-server
  - tigervnc-common
  - ubuntu-desktop-minimal
  - dbus-x11
  - xauth
  - openssh-server
  - qemu-guest-agent

write_files:
  - path: /home/ubuntu/.vnc/xstartup
    owner: ubuntu:ubuntu
    permissions: "0755"
    content: |
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec gnome-session &

  - path: /etc/tigervnc/vncserver.users
    permissions: "0644"
    content: |
      :1=ubuntu

runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - mkdir -p /home/ubuntu/.vnc
  - chown -R ubuntu:ubuntu /home/ubuntu/.vnc
  - touch /home/ubuntu/.Xauthority
  - chown ubuntu:ubuntu /home/ubuntu/.Xauthority
  - chmod 600 /home/ubuntu/.Xauthority
  - su - ubuntu -c "printf 'password\n' | vncpasswd -f > /home/ubuntu/.vnc/passwd"
  - chmod 600 /home/ubuntu/.vnc/passwd
  - systemctl daemon-reload
  - systemctl enable tigervncserver@:1.service
  
