#cloud-config

hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: true
disable_root: true

chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - tigervnc-standalone-server
  - tigervnc-common
  - xfce4
  - xfce4-goodies
  - dbus-x11
  - openssh-server
  - qemu-guest-agent

write_files:
  # xstartup (NO XAUTHORITY)
  - path: /home/ubuntu/.vnc/xstartup
    owner: root:root
    permissions: "0755"
    content: |
      #!/bin/sh
      unset XAUTHORITY
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec startxfce4 &

   # Override service to allow external VNC
  - path: /etc/systemd/system/tigervncserver@:1.service.d/override.conf
    permissions: "0644"
    content: |
      [Service]
      Type=simple
      User=ubuntu
      Environment="HOME=/home/ubuntu"
      ExecStart=
      ExecStart=/usr/bin/vncserver -fg -localhost=no -geometry 1280x720 :1

runcmd:
  - export DEBIAN_FRONTEND=noninteractive

  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

  - mkdir -p /home/ubuntu/.vnc
  - mkdir -p /home/ubuntu/.config/tigervnc
  
  # VNC password (no xauth involved)
  - su - ubuntu -c "printf 'password\npassword\n' | vncpasswd"
  - chmod 600 /home/ubuntu/.vnc/passwd
  - chown ubuntu:ubuntu /home/ubuntu/.vnc/passwd
  - chown ubuntu:ubuntu /home/ubuntu
  - chown ubuntu:ubuntu /home/ubuntu/.vnc
  - chown ubuntu:ubuntu /home/ubuntu/tigervnc
  - echo ":1=ubuntu" > /etc/tigervnc/vncserver.users


  # Enable VNC service
  - systemctl daemon-reload
  - systemctl enable tigervncserver@:1.service

#power_state:
#  mode: reboot
#  message: "Reboot after cloud-init setup"
#  timeout: 30
#  condition: true
