#cloud-config

hostname: client01
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false

package_update: true
package_upgrade: true

write_files:
  - path: /home/ubuntu/.vnc/xstartup
    owner: root:root
    permissions: "0755"
    content: |
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec dbus-launch --exit-with-session startxfce4 &

  - path: /etc/systemd/system/vncserver.service
    permissions: "0644"
    content: |
      [Unit]
      Description=VNC server on display :1
      After=network.target

      [Service]
      Type=forking
      User=ubuntu
      WorkingDirectory=/home/ubuntu
      ExecStart=/usr/bin/vncserver -localhost=no -geometry 1280x720 :1
      ExecStop=/usr/bin/vncserver -kill :1
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target


packages:
  - ubuntu-desktop-minimal
  - gnome-tweaks
 
runcmd:
  - set -x
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -y qemu-guest-agent xfce4 xfce4-goodies xfce4-session tigervnc-standalone-server dbus-x11
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - sed -i 's/^#WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/custom.conf
  - apt-get install -y 
  - mkdir -p /home/ubuntu/.vnc
  - chown -R ubuntu:ubuntu /home/ubuntu
  - systemctl enable ssh
  - systemctl set-default multi-user.target
  - su - ubuntu -c "printf 'password\npassword\n\n' | vncpasswd"
  - systemctl daemon-reload
  - systemctl enable vncserver
  - systemctl start vncserver
  - reboot
