version: "3.9"

services:
  redis:
    image: registry.community.greenbone.net/community/redis-server:stable
    restart: unless-stopped

  postgres:
    image: registry.community.greenbone.net/community/pg-gvm:stable
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql

  gvmd:
    image: registry.community.greenbone.net/community/gvmd:stable
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

  gsa:
    image: registry.community.greenbone.net/community/gsa:stable
    restart: unless-stopped
    depends_on:
      - gvmd

  gsad:
    image: registry.community.greenbone.net/community/gsad:stable
    restart: unless-stopped
    depends_on:
      - gsa
    ports:
      - "9392:9392"

  ospd-openvas:
    image: registry.community.greenbone.net/community/ospd-openvas:stable
    restart: unless-stopped
    depends_on:
      - redis

  openvas:
    image: registry.community.greenbone.net/community/openvas-scanner:stable
    restart: unless-stopped
    depends_on:
      - ospd-openvas

volumes:
  pg_data:
