#cloud-config

hostname: vulnsrv02
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

chpasswd:
  expire: false


packages:
  - ca-certificates
  - curl
  - docker.io

write_files:
  - path: /opt/juiceshop/docker-compose.yml
    owner: root:root
    permissions: '0644'
    content: |
         services:
        
          juiceshop:
            image: bkimminich/juice-shop:latest
            container_name: juiceshop
            restart: unless-stopped
            expose:
              - "3000:3000"
            environment:
              - NODE_ENV=production
              - CTFSHOWDIFFICULTY=1
              - CTF_SHOW_HINTS=true
              - SOLUTIONS=false
            volumes:
              - juice_data:/juice-shop/data
                  
         volumes:
          juice_data:


runcmd:
  - apt-get update
  - apt-get install -y docker-compose-v2 qemu-guest-agent
  - systemctl enable docker
  - systemctl start docker
  - systemctl enable qemu-guest-agent
  - usermod -aG docker ubuntu
  - mkdir -p /opt/juiceshop
 
