#cloud-config

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key
   
chpasswd:
  expire: false

package_update: true
package_upgrade: true

packages:
  - kali-desktop-xfce
  - lightdm
  - lightdm-gtk-greeter
  - xorg
  - dbus-x11
  - qemu-guest-agent
  - openssh-server
  - xfce4-terminal
  - firefox-esr
  - kali-linux-default

timezone: UTC

runcmd:
  - systemctl enable ssh
  - systemctl enable lightdm
  - systemctl enable qemu-guest-agent
  - systemctl set-default graphical.target
  - systemctl start lightdm
  - echo "ZERO TOUCH DESKTOP READY" > /var/log/desktop-installed.log

final_message: |
  ✔ Kali XFCE desktop installed
  ✔ Zero-touch provisioning complete
  ✔ GUI enabled on first boot
