#cloud-config

hostname: kali
manage_etc_hosts: true

users:
  - name: kali
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: false
disable_root: true

chpasswd:
  expire: false

power_state:
  mode: reboot
  message: "Reboot after initial cloud-init setup"
  timeout: 30
  condition: true

packages:
  - kali-desktop-xfce
  - xorg
  - dbus-x11
  - openssh-server
  - tigervnc-standalone-server
  - tigervnc-common
  - curl
  - wireshark
  - ethtool
  - iproute2

write_files:
  - path: /home/kali/.vnc/xstartup
    owner: root:root
    permissions: "0755"
    content: |
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec startxfce4 &

  - path: /etc/systemd/system/vncserver.service
    permissions: "0644"
    content: |
      [Unit]
      Description=TigerVNC server
      After=network.target

      [Service]
      Type=forking
      User=kali
      ExecStart=/usr/bin/vncserver -localhost=no -geometry 1280x720 :1
      ExecStop=/usr/bin/vncserver -kill :1

      [Install]
      WantedBy=multi-user.target

  - path: /etc/profile.d/qt-x11.sh
    permissions: "0644"
    content: |
      export QT_QPA_PLATFORM=xcb

  - path: /usr/local/bin/install-kali-tools.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e
      apt-get update
      apt-get install -y kali-linux-default
      touch /var/lib/kali-tools-installed

  - path: /etc/systemd/system/kali-tools-install.service
    permissions: "0644"
    content: |
      [Unit]
      Description=Install Kali tools after first boot
      After=network-online.target
      Wants=network-online.target
      ConditionPathExists=!/var/lib/kali-tools-installed

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/install-kali-tools.sh

      [Install]
      WantedBy=multi-user.target

runcmd:
  - set -x
  - export DEBIAN_FRONTEND=noninteractive

  # -------------------------
  # Enable SSH
  # -------------------------
  - systemctl enable ssh

  # -------------------------
  # Wireshark non-root capture
  # -------------------------
  - echo "wireshark-common wireshark-common/install-setuid boolean true" | debconf-set-selections
  - dpkg-reconfigure -f noninteractive wireshark-common
  - usermod -aG wireshark kali
  - setcap cap_net_raw,cap_net_admin+eip /usr/bin/dumpcap || true

  # -------------------------
  # Create passive TAP device
  # -------------------------
  - ip tuntap add dev tap_mirror0 mode tap user kali || true
  - ip link set tap_mirror0 up
  - ip addr flush dev tap_mirror0

  # Disable all offloading (failsafe)
  - ethtool -K tap_mirror0 tx off rx off tso off gso off gro off lro off || true

  # -------------------------
  # VNC setup
  # -------------------------
  - mkdir -p /home/kali/.vnc
  - mkdir -p /home/kali/.config/tigervnc
  - chown -R kali:kali /home/kali/.vnc
  - chown -R kali:kali /home/kali/.config
  - su - kali -c "printf 'password\npassword\n' | vncpasswd"
  - systemctl enable vncserver
  - systemctl start vncserver

  # -------------------------
  # Desktop fix for Wireshark
  # -------------------------
  - sed -i 's|^Exec=wireshark|Exec=env QT_QPA_PLATFORM=xcb wireshark|' /usr/share/applications/wireshark.desktop
  - update-desktop-database
  - systemctl daemon-reload
  - systemctl enable kali-tools-install.service
  # -------------------------
  # Optional Kali tools (background)
  # -------------------------
 #  - nohup bash -c "apt-get update && apt-get install -y kali-linux-default" > /var/log/kali-install.log 2>&1 &
