#cloud-config

hostname: kali
manage_etc_hosts: true

users:
  - name: kali1
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

  - name: kali2
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

  - name: kali3
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

  - name: kali4
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: false
disable_root: true

packages:
  - kali-desktop-xfce
  - xorg
  - dbus-x11
  - openssh-server
  - tigervnc-standalone-server
  - tigervnc-common
  - tigervnc-xorg-extension
  - curl
  - wireshark
  - ethtool
  - iproute2
  - qemu-guest-agent

write_files:

  # Default XFCE VNC startup for all users
  - path: /etc/skel/.vnc/xstartup
    permissions: "0755"
    content: |
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec startxfce4 &

  # Map VNC displays to users
  - path: /etc/tigervnc/vncserver.users
    permissions: "0644"
    content: |
      :1=kali1
      :2=kali2
      :3=kali3
      :4=kali4

  # Generic VNC systemd override (works for all users)
  - path: /etc/systemd/system/tigervncserver@.service.d/override.conf
    permissions: "0644"
    content: |
      [Service]
      Type=simple
      ExecStart=
      ExecStart=/usr/bin/vncserver -fg -localhost=no -geometry 1280x800 %i

runcmd:
  - set -e
  - systemctl enable ssh
  - echo "wireshark-common wireshark-common/install-setuid boolean true" | debconf-set-selections
  - dpkg-reconfigure -f noninteractive wireshark-common
  - setcap cap_net_raw,cap_net_admin+eip /usr/bin/dumpcap || true

  # Create VNC dirs
  - for u in kali1 kali2 kali3 kali4; do mkdir -p /home/$u/.vnc; chown -R $u:$u /home/$u/.vnc; done

  # Set simple VNC password (change for production)
  - for u in kali1 kali2 kali3 kali4; do su - $u -c "printf 'password\npassword\n' | vncpasswd"; done

  # Enable all VNC sessions
  - systemctl daemon-reload
  - systemctl enable tigervncserver@:1.service
  - systemctl enable tigervncserver@:2.service
  - systemctl enable tigervncserver@:3.service
  - systemctl enable tigervncserver@:4.service

  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

power_state:
  mode: reboot
