#cloud-config

hostname: kali
manage_etc_hosts: true

users:
  - name: kali
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

  - name: kali1
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0

  - name: kali2
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0

  - name: kali3
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0

  - name: kali4
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0

ssh_pwauth: false
disable_root: true

packages:
  - kali-desktop-xfce
  - openssh-server
  - tigervnc-standalone-server
  - dbus-x11
  - wireshark
  - qemu-guest-agent

runcmd:
  - set -e

  # Create xstartup for all users
  - for u in kali kali1 kali2 kali3 kali4; do \
      mkdir -p /home/$u/.config/tigervnc; \
      echo '#!/bin/sh\nunset SESSION_MANAGER\nunset DBUS_SESSION_BUS_ADDRESS\nexec startxfce4' > /home/$u/.config/tigervnc/xstartup; \
      chmod 755 /home/$u/.config/tigervnc/xstartup; \
      chown -R $u:$u /home/$u/.config; \
    done

  # Set VNC password
  - for u in kali kali1 kali2 kali3 kali4; do \
      su - $u -c "printf 'password\npassword\n' | vncpasswd"; \
    done

  # Create VNC systemd services
  - |
    for i in 1 2 3 4; do
      cat > /etc/systemd/system/vnc-kali${i}.service <<EOF
    [Unit]
    Description=VNC Server for kali${i}
    After=network.target

    [Service]
    Type=forking
    User=kali${i}
    ExecStart=/usr/bin/vncserver -localhost no :${i}
    ExecStop=/usr/bin/vncserver -kill :${i}
    Restart=on-failure

    [Install]
    WantedBy=multi-user.target
    EOF
    done

  - systemctl daemon-reload

  - systemctl enable vnc-kali1
  - systemctl enable vnc-kali2
  - systemctl enable vnc-kali3
  - systemctl enable vnc-kali4

  - systemctl start vnc-kali1
  - systemctl start vnc-kali2
  - systemctl start vnc-kali3
  - systemctl start vnc-kali4

  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

power_state:
  mode: reboot
