#cloud-config

hostname: kali
manage_etc_hosts: true

users:
  - name: kali
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

ssh_pwauth: false
disable_root: true

chpasswd:
  expire: false

packages:
  - kali-desktop-xfce
  - xorg
  - dbus-x11
  - openssh-server
  - tigervnc-standalone-server
  - tigervnc-common
  - curl
  
write_files:
      - path: /home/kali/.vnc/xstartup
        owner: root:root
        permissions: "0755"
        content: |
          #!/bin/sh
    
          unset SESSION_MANAGER
          unset DBUS_SESSION_BUS_ADDRESS
          startxfce4 &
          
      - path: /etc/systemd/system/vncserver.service
        permissions: "0644"
        content: |
          [Unit]
          Description=TightVNC server on Port 5901
          After=Network.target
          
          [Service]
          Type=forking
          User=kali
          ExecStart=/usr/bin/vncserver -localhost=no -geometry 1280x720 :1
          ExecStop=/usr/bin/vncserver -kill :1
          
          [Install]
          WantedBy=multi-user.target

      - path: /etc/profile.d/qt-x11.sh
        permissions: "0644"
        content: |
          export QT_QPA_PLATFORM=xcb


runcmd:
  - set -x
  - export DEBIAN_FRONTEND=noninteractive

  - ip addr flush dev eth2
  - ip link set eth2 up

  # Update repositories
  - apt-get update

  # 1️⃣ Install desktop FIRST
  - apt-get install -y xfce4 xfce4-goodies xfce4-session seclists gobuster whatweb nikto wireshark

  # 2️⃣ Create VNC folders
  - mkdir -p /home/kali/.vnc
  - mkdir -p /home/kali/.config/tigervnc
  - chown -R kali:kali /home/kali

  # 3️⃣ Enable SSH + boot target
  - systemctl enable ssh
  - systemctl set-default multi-user.target

  # 4️⃣ Setup VNC password
  - su - kali -c "printf 'password\npassword\n\n' | vncpasswd"

  # 5️⃣ Enable/start VNC
  - systemctl enable vncserver
  - systemctl start vncserver

  - wget -P /home/kali/Desktop https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/TESTFILES/testips.sh
  - chmod +x /home/kali/Desktop/testips.sh
  - chown kali:kali /home/kali/Desktop/testips.sh

  - sed -i 's|^Exec=wireshark|Exec=env QT_QPA_PLATFORM=xcb wireshark|' /usr/share/applications/wireshark.desktop
  - update-desktop-database
  - dpkg-reconfigure -f noninteractive wireshark-common
  - usermod -aG wireshark kali

  # ⭐ Run Kali tools install in background ⭐
  - nohup bash -c "set -x; export DEBIAN_FRONTEND=noninteractive; apt-get update && apt-get install -y kali-linux-default" > /var/log/kali-install.log 2>&1 &
