#cloud-config

hostname: kali
manage_etc_hosts: true

users:
  - name: kali1
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0

  - name: kali2
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0

  - name: kali3
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0

  - name: kali4
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0

ssh_pwauth: false
disable_root: true

packages:
  - kali-desktop-xfce
  - openssh-server
  - tigervnc-standalone-server
  - dbus-x11
  - wireshark
  - qemu-guest-agent

runcmd:
  - set -e

  # Create proper xstartup (modern Kali path)
  - for u in kali1 kali2 kali3 kali4; do \
      mkdir -p /home/$u/.config/tigervnc; \
      echo '#!/bin/sh\nunset SESSION_MANAGER\nunset DBUS_SESSION_BUS_ADDRESS\nexec startxfce4' > /home/$u/.config/tigervnc/xstartup; \
      chmod 755 /home/$u/.config/tigervnc/xstartup; \
      chown -R $u:$u /home/$u/.config; \
    done

  # Set VNC password for all users
  - for u in kali1 kali2 kali3 kali4; do \
      su - $u -c "printf 'password\npassword\n' | vncpasswd"; \
    done

  # Create systemd service for each user
  - |
    cat > /etc/systemd/system/vnc-kali1.service <<EOF
    [Unit]
    Description=VNC Server for kali1
    After=network.target

    [Service]
    Type=forking
    User=kali1
    ExecStart=/usr/bin/vncserver -localhost no :1
    ExecStop=/usr/bin/vncserver -kill :1
    Restart=on-failure

    [Install]
    WantedBy=multi-user.target
    EOF

  - |
    cat > /etc/systemd/system/vnc-kali2.service <<EOF
    [Unit]
    Description=VNC Server for kali2
    After=network.target

    [Service]
    Type=forking
    User=kali2
    ExecStart=/usr/bin/vncserver -localhost no :2
    ExecStop=/usr/bin/vncserver -kill :2
    Restart=on-failure

    [Install]
    WantedBy=multi-user.target
    EOF

  - |
    cat > /etc/systemd/system/vnc-kali3.service <<EOF
    [Unit]
    Description=VNC Server for kali3
    After=network.target

    [Service]
    Type=forking
    User=kali3
    ExecStart=/usr/bin/vncserver -localhost no :3
    ExecStop=/usr/bin/vncserver -kill :3
    Restart=on-failure

    [Install]
    WantedBy=multi-user.target
    EOF

  - |
    cat > /etc/systemd/system/vnc-kali4.service <<EOF
    [Unit]
    Description=VNC Server for kali4
    After=network.target

    [Service]
    Type=forking
    User=kali4
    ExecStart=/usr/bin/vncserver -localhost no :4
    ExecStop=/usr/bin/vncserver -kill :4
    Restart=on-failure

    [Install]
    WantedBy=multi-user.target
    EOF

  - systemctl daemon-reload

  - systemctl enable vnc-kali1
  - systemctl enable vnc-kali2
  - systemctl enable vnc-kali3
  - systemctl enable vnc-kali4

  - systemctl start vnc-kali1
  - systemctl start vnc-kali2
  - systemctl start vnc-kali3
  - systemctl start vnc-kali4

  - systemctl enable ssh
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

power_state:
  mode: reboot
