#cloud-config

hostname: kali
manage_etc_hosts: true

users:
  - name: kali
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo,wireshark
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key

  - { name: kali1, sudo: ALL=(ALL) NOPASSWD:ALL, groups: sudo,wireshark, shell: /bin/bash, lock_passwd: false, passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0, ssh_authorized_keys: [ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key] }
  - { name: kali2, sudo: ALL=(ALL) NOPASSWD:ALL, groups: sudo,wireshark, shell: /bin/bash, lock_passwd: false, passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0, ssh_authorized_keys: [ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key] }
  - { name: kali3, sudo: ALL=(ALL) NOPASSWD:ALL, groups: sudo,wireshark, shell: /bin/bash, lock_passwd: false, passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0, ssh_authorized_keys: [ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key] }
  - { name: kali4, sudo: ALL=(ALL) NOPASSWD:ALL, groups: sudo,wireshark, shell: /bin/bash, lock_passwd: false, passwd: $6$qTDYvGhBFYXcEuz.$k1DP25NmlgMNIQLbDGCQh8k3zNDLyrdVJ/99ojc3ir5xNjGxvB736GWNHA0LszFPYdIpD4W6Jxhz45ql6LpmM0, ssh_authorized_keys: [ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK9gExgup4UNA3vRiCBKdCK9+IdVKbosvXEDpTrjqGVW shared-admin-key] }

ssh_pwauth: false
disable_root: true

packages:
  - kali-desktop-xfce
  - openssh-server
  - tigervnc-standalone-server
  - dbus-x11
  - wireshark
  - qemu-guest-agent
  - curl
  - ethtool

write_files:

  #########################################################
  # Kali tools auto install
  #########################################################

 - path: /usr/local/bin/install-kali-tools.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      # Force IPv4 to avoid Kali mirror IPv6 TLS issues
      echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4
  
      cat > /etc/apt/sources.list <<EOF
      deb https://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware
      EOF
  
      sleep 10
  
      apt-get update -o Acquire::Retries=5
  
      apt-get install -y --fix-missing \
        kali-linux-default \
        nikto \
        seclists \
        gobuster \
        sqlmap

      touch /var/lib/kali-tools-installed

  - path: /etc/systemd/system/kali-tools-install.service
    permissions: "0644"
    content: |
      [Unit]
      Description=Install Kali tools after first boot
      After=network-online.target
      Wants=network-online.target
      ConditionPathExists=!/var/lib/kali-tools-installed

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/install-kali-tools.sh

      [Install]
      WantedBy=multi-user.target

  #########################################################
  # Mirror eth2
  #########################################################

  - path: /etc/sysctl.d/99-mirror.conf
    permissions: "0644"
    content: |
      net.ipv4.ip_forward=0

  - path: /etc/systemd/system/mirror-eth2.service
    permissions: "0644"
    content: |
      [Unit]
      After=network.target

      [Service]
      Type=oneshot
      ExecStart=/sbin/ip addr flush dev eth2
      ExecStart=/sbin/ip link set eth2 up
      ExecStart=/sbin/ethtool -K eth2 tx off rx off tso off gso off gro off lro off

      [Install]
      WantedBy=multi-user.target

  #########################################################
  # Multi user VNC setup script
  #########################################################

  - path: /usr/local/sbin/setup-vnc-multiuser.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -e

      USERS=(kali kali1 kali2 kali3 kali4)

      for u in "${USERS[@]}"; do
        HOME_DIR=$(getent passwd "$u" | cut -d: -f6)

        mkdir -p "$HOME_DIR/.config/tigervnc"
        mkdir -p "$HOME_DIR/Desktop/IPS"
        mkdir -p "$HOME_DIR/Desktop/wireshark"

        cat > "$HOME_DIR/.config/tigervnc/xstartup" <<'EOF'
      #!/bin/sh
      unset SESSION_MANAGER
      unset DBUS_SESSION_BUS_ADDRESS
      exec dbus-launch --exit-with-session startxfce4
      EOF

        chmod 0755 "$HOME_DIR/.config/tigervnc/xstartup"
        chown -R "$u:$u" "$HOME_DIR/.config"

        # VNC password = password
        su - "$u" -c "printf 'password\npassword\n' | vncpasswd"

        # Download lab files
        wget -q -O "$HOME_DIR/Desktop/IPS/testips.sh" \
          https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/TESTFILES/testips.sh

        wget -q -O "$HOME_DIR/Desktop/wireshark/rsasnakeoil2.cap" \
          https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/TESTFILES/WIRESHARK/rsasnakeoil2.cap

        wget -q -O "$HOME_DIR/Desktop/wireshark/rsasnakeoil2.key" \
          https://raw.githubusercontent.com/EUD-cyber/eud-cyber/main/TESTFILES/WIRESHARK/rsasnakeoil2.key

        chmod +x "$HOME_DIR/Desktop/IPS/testips.sh"
        chown -R "$u:$u" "$HOME_DIR/Desktop"
      done

        # --------------------------------------------------
        # Fix Wireshark permissions for all users
        # --------------------------------------------------
        
        echo "Configuring Wireshark permissions..."
        
        echo "wireshark-common wireshark-common/install-setuid boolean true" | debconf-set-selections
        dpkg-reconfigure -f noninteractive wireshark-common
        
        for u in "${USERS[@]}"; do
          usermod -aG wireshark "$u"
        done
        
        setcap cap_net_raw,cap_net_admin+eip /usr/bin/dumpcap || true
        
        getcap /usr/bin/dumpcap
      create_service() {
        USERNAME=$1
        DISPLAY=$2

        cat > /etc/systemd/system/vnc-${USERNAME}.service <<EOF
      [Unit]
      Description=VNC Server for ${USERNAME}
      After=network.target

      [Service]
      Type=forking
      User=${USERNAME}
      ExecStart=/usr/bin/vncserver -localhost no :${DISPLAY}
      ExecStop=/usr/bin/vncserver -kill :${DISPLAY}
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
      EOF
      }

      create_service kali 0
      create_service kali1 1
      create_service kali2 2
      create_service kali3 3
      create_service kali4 4

      systemctl daemon-reload
      systemctl enable --now vnc-kali.service
      systemctl enable --now vnc-kali1.service
      systemctl enable --now vnc-kali2.service
      systemctl enable --now vnc-kali3.service
      systemctl enable --now vnc-kali4.service
      systemctl enable --now kali-tools-install.service
      systemctl enable --now mirror-eth2.service
      systemctl enable --now ssh
      systemctl enable --now qemu-guest-agent

runcmd:
  - /usr/local/sbin/setup-vnc-multiuser.sh

power_state:
  mode: reboot
